// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.7
// source: message.proto

package message

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 指令类型
type CommandType int32

const (
	// 未知指令
	CommandType_CommandType_Unknow CommandType = 0
	// 握手
	CommandType_CommandType_HandShakeReq CommandType = 1
	// 握手回复
	CommandType_CommandType_HandShakeResp CommandType = 2
	// 心跳
	CommandType_CommandType_Heartbeat CommandType = 3
)

// Enum value maps for CommandType.
var (
	CommandType_name = map[int32]string{
		0: "CommandType_Unknow",
		1: "CommandType_HandShakeReq",
		2: "CommandType_HandShakeResp",
		3: "CommandType_Heartbeat",
	}
	CommandType_value = map[string]int32{
		"CommandType_Unknow":        0,
		"CommandType_HandShakeReq":  1,
		"CommandType_HandShakeResp": 2,
		"CommandType_Heartbeat":     3,
	}
)

func (x CommandType) Enum() *CommandType {
	p := new(CommandType)
	*p = x
	return p
}

func (x CommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_message_proto_enumTypes[0].Descriptor()
}

func (CommandType) Type() protoreflect.EnumType {
	return &file_message_proto_enumTypes[0]
}

func (x CommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *CommandType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = CommandType(num)
	return nil
}

// Deprecated: Use CommandType.Descriptor instead.
func (CommandType) EnumDescriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{0}
}

// 通用消息体
type MSG_BODY struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       *CommandType           `protobuf:"varint,1,req,name=command,enum=pb.CommandType" json:"command,omitempty"`
	Payload       *anypb.Any             `protobuf:"bytes,2,req,name=payload" json:"payload,omitempty"`
	Timestamp     *int64                 `protobuf:"varint,3,req,name=timestamp" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MSG_BODY) Reset() {
	*x = MSG_BODY{}
	mi := &file_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MSG_BODY) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MSG_BODY) ProtoMessage() {}

func (x *MSG_BODY) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MSG_BODY.ProtoReflect.Descriptor instead.
func (*MSG_BODY) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{0}
}

func (x *MSG_BODY) GetCommand() CommandType {
	if x != nil && x.Command != nil {
		return *x.Command
	}
	return CommandType_CommandType_Unknow
}

func (x *MSG_BODY) GetPayload() *anypb.Any {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *MSG_BODY) GetTimestamp() int64 {
	if x != nil && x.Timestamp != nil {
		return *x.Timestamp
	}
	return 0
}

// 握手消息
type MSG_HANDSHAKE_REQ struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       *string                `protobuf:"bytes,1,req,name=version" json:"version,omitempty"`   // 协议版本号
	DeviceId      *string                `protobuf:"bytes,2,req,name=deviceId" json:"deviceId,omitempty"` // 设备ID（暂时用FQDN代替）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MSG_HANDSHAKE_REQ) Reset() {
	*x = MSG_HANDSHAKE_REQ{}
	mi := &file_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MSG_HANDSHAKE_REQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MSG_HANDSHAKE_REQ) ProtoMessage() {}

func (x *MSG_HANDSHAKE_REQ) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MSG_HANDSHAKE_REQ.ProtoReflect.Descriptor instead.
func (*MSG_HANDSHAKE_REQ) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{1}
}

func (x *MSG_HANDSHAKE_REQ) GetVersion() string {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return ""
}

func (x *MSG_HANDSHAKE_REQ) GetDeviceId() string {
	if x != nil && x.DeviceId != nil {
		return *x.DeviceId
	}
	return ""
}

// 握手响应
type MSG_HANDSHAKE_RESP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          *int32                 `protobuf:"varint,1,req,name=code" json:"code,omitempty"`      // 响应码（0=成功）
	Message       *string                `protobuf:"bytes,2,req,name=message" json:"message,omitempty"` // 错误信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MSG_HANDSHAKE_RESP) Reset() {
	*x = MSG_HANDSHAKE_RESP{}
	mi := &file_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MSG_HANDSHAKE_RESP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MSG_HANDSHAKE_RESP) ProtoMessage() {}

func (x *MSG_HANDSHAKE_RESP) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MSG_HANDSHAKE_RESP.ProtoReflect.Descriptor instead.
func (*MSG_HANDSHAKE_RESP) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{2}
}

func (x *MSG_HANDSHAKE_RESP) GetCode() int32 {
	if x != nil && x.Code != nil {
		return *x.Code
	}
	return 0
}

func (x *MSG_HANDSHAKE_RESP) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

// 心跳消息
type MSG_HEARTBEAT struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Os            *string                `protobuf:"bytes,1,req,name=os" json:"os,omitempty"`
	Cpu           *float64               `protobuf:"fixed64,2,req,name=cpu" json:"cpu,omitempty"` // cpu使用率(float64)
	Mem           *float64               `protobuf:"fixed64,3,req,name=mem" json:"mem,omitempty"` // 内存使用率(float64)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MSG_HEARTBEAT) Reset() {
	*x = MSG_HEARTBEAT{}
	mi := &file_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MSG_HEARTBEAT) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MSG_HEARTBEAT) ProtoMessage() {}

func (x *MSG_HEARTBEAT) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MSG_HEARTBEAT.ProtoReflect.Descriptor instead.
func (*MSG_HEARTBEAT) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{3}
}

func (x *MSG_HEARTBEAT) GetOs() string {
	if x != nil && x.Os != nil {
		return *x.Os
	}
	return ""
}

func (x *MSG_HEARTBEAT) GetCpu() float64 {
	if x != nil && x.Cpu != nil {
		return *x.Cpu
	}
	return 0
}

func (x *MSG_HEARTBEAT) GetMem() float64 {
	if x != nil && x.Mem != nil {
		return *x.Mem
	}
	return 0
}

var File_message_proto protoreflect.FileDescriptor

const file_message_proto_rawDesc = "" +
	"\n" +
	"\rmessage.proto\x12\x02pb\x1a\x19google/protobuf/any.proto\"\x83\x01\n" +
	"\bMSG_BODY\x12)\n" +
	"\acommand\x18\x01 \x02(\x0e2\x0f.pb.CommandTypeR\acommand\x12.\n" +
	"\apayload\x18\x02 \x02(\v2\x14.google.protobuf.AnyR\apayload\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x02(\x03R\ttimestamp\"I\n" +
	"\x11MSG_HANDSHAKE_REQ\x12\x18\n" +
	"\aversion\x18\x01 \x02(\tR\aversion\x12\x1a\n" +
	"\bdeviceId\x18\x02 \x02(\tR\bdeviceId\"B\n" +
	"\x12MSG_HANDSHAKE_RESP\x12\x12\n" +
	"\x04code\x18\x01 \x02(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x02(\tR\amessage\"C\n" +
	"\rMSG_HEARTBEAT\x12\x0e\n" +
	"\x02os\x18\x01 \x02(\tR\x02os\x12\x10\n" +
	"\x03cpu\x18\x02 \x02(\x01R\x03cpu\x12\x10\n" +
	"\x03mem\x18\x03 \x02(\x01R\x03mem*}\n" +
	"\vCommandType\x12\x16\n" +
	"\x12CommandType_Unknow\x10\x00\x12\x1c\n" +
	"\x18CommandType_HandShakeReq\x10\x01\x12\x1d\n" +
	"\x19CommandType_HandShakeResp\x10\x02\x12\x19\n" +
	"\x15CommandType_Heartbeat\x10\x03B\fZ\n" +
	"./;message"

var (
	file_message_proto_rawDescOnce sync.Once
	file_message_proto_rawDescData []byte
)

func file_message_proto_rawDescGZIP() []byte {
	file_message_proto_rawDescOnce.Do(func() {
		file_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_message_proto_rawDesc), len(file_message_proto_rawDesc)))
	})
	return file_message_proto_rawDescData
}

var file_message_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_message_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_message_proto_goTypes = []any{
	(CommandType)(0),           // 0: pb.CommandType
	(*MSG_BODY)(nil),           // 1: pb.MSG_BODY
	(*MSG_HANDSHAKE_REQ)(nil),  // 2: pb.MSG_HANDSHAKE_REQ
	(*MSG_HANDSHAKE_RESP)(nil), // 3: pb.MSG_HANDSHAKE_RESP
	(*MSG_HEARTBEAT)(nil),      // 4: pb.MSG_HEARTBEAT
	(*anypb.Any)(nil),          // 5: google.protobuf.Any
}
var file_message_proto_depIdxs = []int32{
	0, // 0: pb.MSG_BODY.command:type_name -> pb.CommandType
	5, // 1: pb.MSG_BODY.payload:type_name -> google.protobuf.Any
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_message_proto_init() }
func file_message_proto_init() {
	if File_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_message_proto_rawDesc), len(file_message_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_proto_goTypes,
		DependencyIndexes: file_message_proto_depIdxs,
		EnumInfos:         file_message_proto_enumTypes,
		MessageInfos:      file_message_proto_msgTypes,
	}.Build()
	File_message_proto = out.File
	file_message_proto_goTypes = nil
	file_message_proto_depIdxs = nil
}
